[package]
name = "snake"
version = "0.1.0"
authors = ["molko-did-a-nerd-stuff <0824molo@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
raylib = "*"
glm = "*"